import {Dimensions, StyleSheet} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export default StyleSheet.create({
  alan1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  menuIcons: {
    width: 27,
    height: 27,
    justifyContent: 'flex-start',
    tintColor: 'black',
    marginTop: 10,
    marginLeft: 8,
  },
  text1: {
    fontWeight: 'bold',
    fontSize: 27,
    color: '#5F60E0',
  },
  text2: {
    fontWeight: 'bold',
    fontSize: 22,
    color: '#D7C0FF',
    marginTop: 6,
  },
  textBar: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 9,
  },
  iconsBell: {
    width: 27,
    height: 27,
    justifyContent: 'flex-end',
    tintColor: 'black',
    marginTop: 10,
    marginRight: 8,
  },
  textGreet: {
    color: 'black',
    fontSize: 17,
    fontWeight: '400',
    marginTop: 76,
    marginLeft: 12,
  },
  textHaydi: {
    color: 'black',
    fontSize: 26,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  line: {
    padding: 2,
    width: windowWidth * 1,
    marginTop: 12,
  },
  alan2: {
    padding: 9,
    borderRadius: 16,
    backgroundColor: 'white',
    alignSelf: 'center',
    width: windowWidth * 0.7,
    marginTop: 14,
    shadowColor: '#000', // iOS için
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  backgrounnddd: {
    flex: 1,
    backgroundColor: '#F4F4F4',
  },
  alan2Yan: {
    flexDirection: 'row',
    gap: 13,
  },
  searchicons: {
    width: 19,
    height: 19,
    tintColor: '#418CE7',
    marginTop: 10,
    marginLeft: 6,
  },
  inputText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#948D8D',
  },
  daire1: {
    width: 67,
    height: 67,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: '#2498E7',
    marginLeft: 8,
  },
  daire1icon: {
    width: 62,
    height: 62,
    borderRadius: 45,
  },
  alan3Scrooll: {
    flexDirection: 'row',
    marginTop: 18,
    maxHeight: 92,
  },
  alan3ScrollTextAlani: {
    height: 87,
    backgroundColor: '#F4F4F4',
    width: 79,
    marginLeft: 21,
  },
  scrollText:{
   fontSize:12,
   fontWeight:'400',
   color:'black',
   marginLeft:12,
   marginTop:3
  },
  textDaire: {
    fontSize: 12,
    fontWeight: '400',
    color: 'white',
  },
  alan4: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  alan4Text1: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 14,
  },
  alan4Text2: {
    color: 'black',
    fontSize: 12,
    fontWeight: '400',
    marginRight: 11,
  },
  imageBack: {
    width: 178,
    height: 248,
    borderRadius: 15,
  },
  alan5Daire: {
    padding: 17,
    borderRadius: 24,
    backgroundColor: '#878488',
    width: 10,
    alignSelf: 'flex-end',
    margin: 5,
    justifyContent: 'center',
    maxHeight:21,
  },
  hearticon: {
    width: 18,
    height: 17,
    alignSelf: 'center',
    tintColor: 'white',
  },
  text23: {
    fontSize: 19,
    fontWeight: '500',
    color: 'black',
    marginTop: 17,
  },
  text24: {
    fontSize: 13,
    fontWeight: '500',
    color: 'black',
  },
  text34: {
    fontSize: 13,
    fontWeight: '300',
    color: 'black',
    marginTop: 12,
  },
  alanimages2: {
    width: 140,
    height: 155,
    marginTop: 12,
    borderRadius: 15,
    marginLeft: 13,
  },
  images2: {
    width: windowWidth * 0.9,
    height: windowWidth * 0.4,
    borderRadius: 15,
    backgroundColor: 'white',
    alignSelf: 'center',
    marginTop: 14,
  },
  textScroll: {
    fontSize: 13,
    fontWeight: '400',
    color: 'black',
    marginLeft: 17,
  },
  imageAciklama: {
    flexDirection: 'row',
    gap: 13,
    justifyContent: 'flex-start',
    marginTop: 176,
  },
  circleicon: {
    width: 18,
    height: 18,
    marginLeft: 14,
    tintColor: 'white',
  },
  circleText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'white',
  },
});
